periodics:
- name: ci-gardener-e2e-kind-gardenadm-unmanaged-infra-restore
  cluster: gardener-prow-build
  interval: 2h
  extra_refs:
  - org: gardener
    repo: gardener
    base_ref: master
  decorate: true
  decoration_config:
    timeout: 2h
    grace_period: 15m
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-gocache-mounts: "true"
  annotations:
    description: Runs end-to-end tests periodically for gardenadm unmanaged infrastructure restore developments with self-contained Gardener
    testgrid-dashboards: gardener-gardener
    testgrid-days-of-results: "60"
    fork-per-release: "true"
  spec:
    serviceAccountName: gardener-prow-gobuildcache-rw
    containers:
    - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20260916-a163647-1.26
      command:
      - wrapper.sh
      - bash
      - -c
      - make import-tools-bin ci-e2e-kind-gardenadm-unmanaged-infra-restore
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 14
          memory: 24Gi
      env:
      - name: GOCACHEPROG
        value: "gobuildcache gs://gardener-prow-gobuildcache"
      - name: SKAFFOLD_UPDATE_CHECK
        value: "false"
      - name: SKAFFOLD_INTERACTIVE
        value: "false"