presubmits:
  gardener/gardener-extension-shoot-lakom-service:
    - name: pull-gardener-extension-shoot-lakom-service-e2e-kind
      cluster: gardener-prow-build
      always_run: false
      skip_if_only_changed: "^(\\.ci|\\.github|\\.ocm|\\.test-defs|docs)/|\\.md$|^(README|LICENSE|VERSION|OWNERS|OWNERS_ALIASES)$"
      decorate: true
      decoration_config:
        timeout: 1h10m
        grace_period: 15m
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        description: Runs end-to-end tests for gardener-extension-shoot-lakom-service developments in pull requests
      spec:
        containers:
          - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20260827-862f30e-1.26
            command:
              - wrapper.sh
              - bash
              - -c
              - make import-tools-bin ci-e2e-kind
            # we need privileged mode in order to do docker in docker
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10
                memory: 20Gi
            env:
              - name: SKAFFOLD_UPDATE_CHECK
                value: "false"
              - name: SKAFFOLD_INTERACTIVE
                value: "false"
periodics:
  - name: ci-gardener-extension-shoot-lakom-service-e2e-kind
    cluster: gardener-prow-build
    interval: 24h
    extra_refs:
      - org: gardener
        repo: gardener-extension-shoot-lakom-service
        base_ref: main
    decorate: true
    decoration_config:
      timeout: 1h10m
      grace_period: 15m
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      description: Runs end-to-end tests for gardener-extension-shoot-lakom-service developments periodically
      testgrid-dashboards: gardener-extension-shoot-lakom-service
      testgrid-days-of-results: "60"
    spec:
      containers:
        - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/krte:v20260827-862f30e-1.26
          command:
            - wrapper.sh
            - bash
            - -c
            - make import-tools-bin ci-e2e-kind
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 10
              memory: 20Gi
          env:
            - name: SKAFFOLD_UPDATE_CHECK
              value: "false"
            - name: SKAFFOLD_INTERACTIVE
              value: "false"
