{
 "title": "Boskos Resource Usage",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "AWS account usage status",
   "type": "graph",
   "description": "The number of AWS accounts in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"aws-account\",job=\"k8s-prow-builds-new-boskos\"} or boskos_resources{type=\"aws-account\",instance=\"104.197.27.114:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GCE project usage status",
   "type": "graph",
   "description": "The number of GCE projects in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gce-project\",job=\"k8s-prow-builds-new-boskos\"} or boskos_resources{type=\"gce-project\",instance=\"104.197.27.114:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GCE project (k8s-infra) usage status",
   "type": "graph",
   "description": "The number of GCE project (k8s-infra)s in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gce-project\",job=\"k8s-infra-prow-builds-boskos\"} or boskos_resources{type=\"gce-project\",instance=\"35.225.208.117:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GPU project usage status",
   "type": "graph",
   "description": "The number of GPU projects in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gpu-project\",job=\"k8s-prow-builds-new-boskos\"} or boskos_resources{type=\"gpu-project\",instance=\"104.197.27.114:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GPU project (k8s-infra) usage status",
   "type": "graph",
   "description": "The number of GPU project (k8s-infra)s in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"gpu-project\",job=\"k8s-infra-prow-builds-boskos\"} or boskos_resources{type=\"gpu-project\",instance=\"35.225.208.117:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Ingress project usage status",
   "type": "graph",
   "description": "The number of Ingress projects in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"ingress-project\",job=\"k8s-prow-builds-new-boskos\"} or boskos_resources{type=\"ingress-project\",instance=\"104.197.27.114:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Node e2e project usage status",
   "type": "graph",
   "description": "The number of Node e2e projects in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"node-e2e-project\",job=\"k8s-prow-builds-new-boskos\"} or boskos_resources{type=\"node-e2e-project\",instance=\"104.197.27.114:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Scalability project usage status",
   "type": "graph",
   "description": "The number of Scalability projects in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"scalability-project\",job=\"k8s-prow-builds-new-boskos\"} or boskos_resources{type=\"scalability-project\",instance=\"104.197.27.114:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Scalability project (k8s-infra) usage status",
   "type": "graph",
   "description": "The number of Scalability project (k8s-infra)s in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"scalability-project\",job=\"k8s-infra-prow-builds-boskos\"} or boskos_resources{type=\"scalability-project\",instance=\"35.225.208.117:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Scalability presubmit project usage status",
   "type": "graph",
   "description": "The number of Scalability presubmit projects in each state.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(boskos_resources{type=\"scalability-presubmit-project\",job=\"k8s-prow-builds-new-boskos\"} or boskos_resources{type=\"scalability-presubmit-project\",instance=\"104.197.27.114:9090\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}