{
 "title": "sinker dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "time used in each sinker cleaning",
   "type": "graph",
   "description": "sum(sinker_loop_duration_seconds)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_loop_duration_seconds)"
    }
   ]
  },
  {
   "title": "existing pods/prow jobs",
   "type": "graph",
   "description": "sum(sinker_pods_existing) and sum(sinker_prow_jobs_existing)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sinker_pods_existing)" },
    { "expr": "sum(sinker_prow_jobs_existing)" }
   ]
  },
  {
   "title": "removed pods",
   "type": "graph",
   "description": "sum(sinker_pods_removed) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_pods_removed) by (reason)"
    }
   ]
  },
  {
   "title": "cleaned prow jobs",
   "type": "graph",
   "description": "sum(sinker_prow_jobs_cleaned) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_prow_jobs_cleaned) by (reason)"
    }
   ]
  },
  {
   "title": "errors occurred in pod cleaning",
   "type": "graph",
   "description": "sum(sinker_pod_removal_errors) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_pod_removal_errors) by (reason)"
    }
   ]
  },
  {
   "title": "errors occurred in prow job cleaning",
   "type": "graph",
   "description": "sum(sinker_prow_jobs_cleaning_errors) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_prow_jobs_cleaning_errors) by (reason)"
    }
   ]
  }
 ]
}