presubmits:
  gardener/ci-infra:
  # Please keep this in sync with the `ci-infra-prow-checkconfig-{trusted,build}` jobs
  - name: pull-ci-infra-prow-checkconfig
    cluster: gardener-prow-build
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    decorate: true
    annotations:
      description: Runs checkconfig to validate changes to job configs, config.yaml and friends
    spec:
      containers:
      - image: us-docker.pkg.dev/k8s-infra-prow/images/checkconfig:v20260328-dc2bbc9fc
        command:
        - checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --job-config-path=config/jobs
        - --plugin-config=config/prow/plugins.yaml
        - --strict
        - --warnings=mismatched-tide-lenient
        - --warnings=tide-strict-branch
        - --warnings=needs-ok-to-test
        - --warnings=validate-owners
        - --warnings=missing-trigger
        - --warnings=validate-urls
        - --warnings=unknown-fields
        - --warnings=duplicate-job-refs
  - name: pull-ci-infra-prow-go-tests
    cluster: gardener-prow-build
    decorate: true
    skip_if_only_changed: '^(.github|clusters|config|deploy|images)\/'
    annotations:
      description: Runs go tests for prow developments in ci-infra 
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/golang-test:v20260331-1b19063-1.26
        command:
        - make
        args:
        - verify
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 4
            memory: 2Gi
  - name: pull-ci-infra-verify-image-build
    cluster: gardener-prow-build
    skip_if_only_changed: '^(clusters|config|deploy)\/'
    annotations:
      description: Verify ci-infra image build on pull requests to master branch
    decorate: true
    labels:
      preset-buildkit-testbuild: "true"
    spec:
      containers:
      - name: buildkit
        image: moby/buildkit:v0.28.1-rootless
        command:
        - /usr/local/bin/buildctl-testbuild-daemonless.sh
        args:
        - --context
        - /home/prow/go/src/github.com/gardener/ci-infra
        - --dockerfile
        - /home/prow/go/src/github.com/gardener/ci-infra
        - --build-arg
        - GOPROXY=http://athens-proxy.athens.svc.cluster.local,direct
        - --target
        - branch-cleaner
        - --target
        - cherrypicker
        - --target
        - cla-assistant
        - --target
        - image-builder
        - --target
        - job-forker
        - --target
        - milestone-activator
        - --target
        - release-handler
        readinessProbe:
          exec:
            command:
              - buildctl
              - debug
              - workers
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
              - buildctl
              - debug
              - workers
          initialDelaySeconds: 5
          periodSeconds: 30
        securityContext:
          seccompProfile:
            type: Unconfined
          appArmorProfile:
            type: Unconfined
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            cpu: 6
            memory: 7Gi
