#!/usr/bin/env bash
# Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

prometheus_operator_version="v0.52.1"

tmp_dir=$(mktemp -d)
trap "rm -rf $tmp_dir" EXIT

rm *.yaml

curl -sSLo - https://github.com/prometheus-operator/prometheus-operator/archive/refs/tags/$prometheus_operator_version.tar.gz | \
  tar -xzf - --strip-components=3 --wildcards "prometheus-operator-*/example/prometheus-operator-crd/*.yaml"

cat <<EOF > README.md
The CRDs in this directory were downloaded from
https://github.com/prometheus-operator/prometheus-operator/tree/$prometheus_operator_version/example/prometheus-operator-crd.

Bump the version in [\`update-crds.sh\`](./update-crds.sh) and run the script to update the CRDs.
EOF

cat <<EOF > kustomization.yaml
# Code generated by $(basename $0), DO NOT EDIT.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
$(ls *.yaml | sed 's/^/- /')
EOF
