presubmits:
  gardener/org:
  - name: pull-org-peribolos-checkconfig
    cluster: gardener-prow-build
    run_if_changed: '^config/org\.yaml$'
    decorate: true
    annotations:
      description: Runs peribolos-checkconfig to validate changes to org config
    spec:
      containers:
      - image: europe-docker.pkg.dev/gardener-project/releases/ci-infra/peribolos-checkconfig:v20260722-e190a29
        command:
        - /peribolos-checkconfig
        args:
            - --min-admins=5
            - --config-path=config/org.yaml
            - --required-admins=gardener-ci-robot
