apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: envoy-gateway
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envoy-gateway
  updatePolicy:
    updateMode: InPlaceOrRecreate
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: envoy-gateway
  name: envoy-prow
  namespace: envoy-gateway-system
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envoy-prow
  updatePolicy:
    updateMode: InPlaceOrRecreate
