{
 "title": "deck dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "path",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, path)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, method)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, status)"
   }
  ]
 },
 "panels": [
  {
   "title": "median latency with (pre-defined) paths, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"<path>\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/tide\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/tide"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/plugin-help.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/plugin-help.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/prowjobs.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/prowjobs.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/pr-data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/log\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/log"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/rerun\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/rerun"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/spyglass/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/spyglass/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/view/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/view/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/job-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/job-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/pr-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{path=\"others\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "latency percentile with path ${path}, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "traffic: couter by status with path ${path} and method ${method}",
   "type": "graph",
   "description": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m])) by (status)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "status percentage with path ${path} and method ${method}",
   "type": "graph",
   "description": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"n..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\"}[5m]))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"2..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"3..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"4..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"5..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "apdex score with target 2.5s and tolerance 10s, path ${path}, method ${method}, and status ${status}",
   "type": "graph",
   "description": "( sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"2.5\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) + sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"10\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) ) / 2 / sum(rate(deck_http_request_duration_seconds_count{path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"2.5\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) + sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"10\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) ) / 2 / sum(rate(deck_http_request_duration_seconds_count{path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job)"
    }
   ]
  },
  {
   "title": "median response size with (pre-defined) paths, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"<path>\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/tide\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/tide"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/plugin-help.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/plugin-help.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/prowjobs.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/prowjobs.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/pr-data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/log\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/log"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/rerun\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/rerun"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/spyglass/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/spyglass/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/view/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/view/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/job-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/job-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/pr-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{path=\"others\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "others"
    }
   ]
  }
 ]
}