{
 "title": "SLO Compliance Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Prow overall SLO compliance",
   "type": "graph",
   "description": "slo_prow_ok",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(slo_prow_ok, \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "deck SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"deck\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"deck\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "hook SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"hook\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"hook\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "prow-controller-manager SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"prow-controller-manager\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"prow-controller-manager\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "sinker SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"sinker\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"sinker\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "tide SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"tide\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"tide\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "monitoring SLO compliance",
   "type": "graph",
   "description": "slo_component_ok{slo=\"monitoring\"}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Compliant (T/F)" }
   ],
   "targets": [
    {
     "expr": "label_replace(min(slo_component_ok{slo=\"monitoring\"}) without (slo), \"__name__\", \"SLO\", \"\", \"\")"
    }
   ]
  }
 ]
}