apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  values:
    alertmanager:
      templateFiles:
        cluster-name.tmpl: |-
          {{ define "cluster_name" }}Trusted Cluster{{ end }}

    prometheus:
      prometheusSpec:
        retention: 90d
